name: Validate with hassfest

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  hassfest:
    name: Run hassfest validation
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run hassfest
        uses: home-assistant/actions/hassfest@main
